package com.izooto;


public interface AppConstant {
    String APP_NAME_TAG = "iZooto";
    String FCM_DEVICE_TOKEN = "deviceToken";
    String SDKNAME = "IZOOTO";
    String DEVICETOKEN="DEVICE TOKEN   ->  ";
    String UTF="UTF-8";
    String FCMDEFAULT="[DEFAULT]";
    String BROWSERKEYID="{BROWSERKEYID}";
    String PTE="2";
    String ANDROIDVERSION = "osVersion";
    String DEVICENAME ="deviceName";
    String TOKEN="at";
    String ADDURL="s";
    String  PID="pid";
    String BTYPE_="btype";
    String DTYPE_="dtype";
    String TIMEZONE="tz";
    String APPVERSION="bver";
    String OS="os";
    String ALLOWED_="allowed";
    String CHECKSDKVERSION="check";
    String LANGUAGE="ln";
    String CLICKINDEX= "clickIndex";
    String APPPID="pid";
    String ENCRYPTED_PID="encryptedPid";
    String ADVERTISING_ID = "add";
    String GET_NOTIFICATION_ENABLED="enable";
    String GET_NOTIFICATION_DISABLED="disable";
    String FIREBASE_ANALYTICS_TRACK = "isCheck";
    String TRACK_NOTIFICATION_ID = "notificationId";
    String IS_NOTIFICATION_ID_UPDATED = "notificationIdUpdated";
    String NOTIFICATION_COUNT = "count";
    String LOG_EVENT = "logEvent";
    String GET_FIREBASE_INSTANCE = "getInstance";
    String UTM_SOURCE = "utm_source";
    String UTM_MEDIUM = "utm_medium";
    String UTM_CAMPAIGN = "utm_campaign";
    String UTM_TERM = "utm_term";
    String UTM_CONTENT = "utm_content";
    String SOURCE = "source";
    String MEDIUM = "medium";
    String FIREBASE_NOTIFICATION_ID = "notification_id";
    String FIREBASE_CAMPAIGN = "campaign";
    String TERM = "term";
    String CONTENT = "content";
    String TIME_OF_CLICK = "time_of_click";
    String FIREBASE_12PM = "12:00:00 PM";
    String FIREBASE_2PM = "02:00:00 PM";
    String FIREBASE_4PM = "04:00:00 PM";
    String FIREBASE_6PM = "06:00:00 PM";
    String FIREBASE_8PM = "08:00:00 PM";
    String FIREBASE_10PM = "10:00:00 PM";
    String FIREBASE_12AM = "12:00:00 AM";
    String FIREBASE_2AM = "02:00:00 AM";
    String FIREBASE_4AM = "04:00:00 AM";
    String FIREBASE_6AM = "06:00:00 AM";
    String FIREBASE_8AM = "08:00:00 AM";
    String FIREBASE_10AM = "10:00:00 AM";
    String FIREBASE_12to2PM = "12-2 PM";
    String FIREBASE_2to4PM = "2-4 PM";
    String FIREBASE_4to6PM = "4-6 PM";
    String FIREBASE_6to8PM = "6-8 PM";
    String FIREBASE_8to10PM = "8-10 PM";
    String FIREBASE_10to12AM = "10-12 AM";
    String FIREBASE_12to2AM = "12-2 AM";
    String FIREBASE_2to4AM = "2-4 AM";
    String FIREBASE_4to6AM = "4-6 AM";
    String FIREBASE_6to8AM = "6-8 AM";
    String FIREBASE_8to10AM = "8-10 AM";
    String FIREBASE_10to12PM = "10-12 PM";
    String PTE_="pte";
    String CID_="cid";
    String RID_="rid";
    String NOTIFICATION_OP="op";
    String ACTION="action";
    String PT_="pt";
    int PT = 0;
    String GE_ ="ge";
    String ET_ ="et";
    String VAL ="val";
    String ACT ="act";
    String BUTTON_ID_1 ="button1ID";
    String BUTTON_TITLE_1 ="button1Title";
    String BUTTON_URL_1 ="button1URL";
    String ADDITIONAL_DATA ="additionalData";
    String LANDING_URL ="landingURL";
    String BUTTON_ID_2 ="button2ID";
    String BUTTON_TITLE_2 ="button2Title";
    String BUTTON_URL_2 ="button2URL";
    String ACTION_TYPE ="actionType";
    String DEFAULT_ICON ="default";
    int GE = 1;
    String IZOOTO_APP_ID = "izooto_app_id";
    String KEY_WEB_URL = "WEB_URL";
    String KEY_NOTIFICITON_ID = "keyNotificationId";
    String IS_TOKEN_UPDATED = "isTokenUpdated";
    String DEVICE_REGISTRATION_TIMESTAMP = "deviceRegistrationTimeStamp";
    String KEY_IN_APP = "keyInApp";
    String  KEY_IN_CID = "cid";
    String KEY_IN_RID = "rid";
    String KEY_IN_BUTOON="btn";
    String KEY_IN_ADDITIONALDATA="ap";
    String KEY_IN_PHONE ="call";
    String KEY_IN_ACT1ID = "act1ID";
    String KEY_IN_ACT2ID="act2ID";
    int BTYPE = 9;
    int DTYPE = 3;
    int SDKOS = 4;
    int ALLOWED = 1;
    int STYPE = 2;
    String SECRETKEY = "b07dfa9d56fc64df";
    String MESSAGE = "It seems you forgot to configure izooto_app id or izooto_sender_id property in your app level build.gradle";
    String FCMERROR = "Unable to generate FCM token, there may be something wrong with sender id";
    String SUCCESS = " Request Successful: ";
    String FAILURE = " Request Failed: ";
    String ATTACHREQUEST = "IZooTo RestClient: ResponseHandler is not attached for the Request: ";
    String EXCEPTIONERROR = "Thrown Error";
    String CDN = "https://cdn.izooto.com/app/app_";
    String MISSINGID="App Id is missing.";
    // Register String
    String SENDERID ="senderId";
    String APPID = "appId";
    String APIKEY="apiKey";
    String ID ="id";
    String RID= "rid";
    String TAG= "tag";
    String ACT1ID="act1id";
    String ACT2ID ="act2id";
    String FIREBASEEXCEPTION ="exception";
    String FCMNAME = "FireBase Name";
    String NOTIFICATIONRECEIVED ="Short lived task is done.";
    String CHECKFCMLIBRARY="The FCM library is missing! Please make sure to include it in your project.";
    //API
    String APISUCESS ="API SUCCESS";
    String APIFAILURE ="API FAILURE";
    String TELIPHONE = "tel:";
    String NO = "NO";
    //// short payload
    String webViewData = "WebViewClient: shouldOverrideUrlLoading";
    String LANDINGURL="landingURL";
    String ACT1URL = "act1URL";
    String ACT2URL="act2URL";
    String ACT1TITLE="act1title";
    String ACT2TITLE="act2title";

    String URL_FWD="&frwd";
    String URL_FWD_="&frwd=";
    String URL_BKEY="&bkey=";
    String URL_ID="id";
    String URL_CLIENT="client";
    String URL_RID="rid";
    String URL_BKEY_="bkey";
    String URL_FRWD___="frwd";
    String FCM_TIME_FORMAT="hh:mm:ss aa";
    String NULL="null";
    String POST="POST";
    String CONTENT_TYPE="Content-Type";
    String FORM_URL_ENCODED="application/x-www-form-urlencoded";
    String FORM_URL_JSON="application/json; charset=UTF-8";
    String DAT=".dat";
    String HTTPS="https:";
    String HTTP="http:";
    String IMPR="impr.izooto.com";
    String KEY_NOT_FOUND="KEY NOT FOUND";
    String GET_TOPIC_NAME = "getTopicName";
    String REMOVE_TOPIC_NAME = "removeTopicName";
    String ADD_TOPIC ="add_topic";
    String REMOVE_TOPIC ="remove_topic";
    String TOPIC ="topic";
    String ANDROID_ID="bKey";
    String ADVERTISEMENTID="adid";
    String LASTCLICKINDEX= "lastclickIndex";
    String LAST_WEBSITE_VISIT= "last_website_visit";
    String LANG_= "lang";
    String CURRENT_DATE= "currentDate";
    String VER_= "ver";
    String ISID_= "isid";
    String IS_HYBRID_SDK = "hybrid";
    String CURRENT_DATE_VIEW = "currentDateView";
    String CURRENT_DATE_CLICK = "currentDateClick";

    String SDKVERSION="2.2.1";
    String QSDK_VERSION="av";
    String SDK="SDKVERSION";
    String AD_NETWORK="an";
    String GLOBAL="g";
    String AD_TYPE="tp";
    String NOTIFICATION_MESSAGE="Send Notification";
    String YES="yes";
    String PACKAGE_NAME="mpn";
    String MEDIATION="Mediation";
    String SDKTYPE="sn";
    String CFGFORDOMAIN= "cfgfordomain";
    String LAST_NOTIFICAION_CLICKED= "last_notification_clicked";
    String LAST_NOTIFICAION_VIEWED= "last_notification_viewed";
    String CURRENT_DATE_VIEW_WEEKLY = "currentDateViewWeekly";
    String CURRENT_DATE_VIEW_DAILY = "currentDateViewDaily";
    String CURRENT_DATE_CLICK_WEEKLY = "currentDateClickWeekly";
    String CURRENT_DATE_CLICK_DAILY = "currentDateClickDaily";
    String PAYLOAD_JSONARRAY = "payloadJsonArray";
    String CHARSET_="charset";
    String UTF_="utf-8";
    String CONTENT_L="Content-Length";
    String USERP_="userp";
    String EXCEPTION_ = "exceptionName";
    String METHOD_NAME = "methodName";
    String ClASS_NAME = "className";
    String APPName_2="NotificationEventManager";
    String APPName_3="NotificationActionManager";
    String USER_LOCAL_DATA = "iz_userLocalData";
    String EVENT_LOCAL_DATA_EN = "eventLocalDataEN";
    String EVENT_LOCAL_DATA_EV = "eventLocalDataEV";
    String SET_SUBSCRITION_LOCAL_DATA = "setSubscriptionLocalData";
    String IS_SET_SUBSCRIPTION_METHOD = "isSetSubscriptionMethod";
    String NOTIFICATION_PREVIEW = "iz_notification_preview";
    String DEVICE_ID = "{~DEVICEID~}";
    String ANDROID_TOKEN = "{~TOKEN~}";
    String R_FCM_TOKEN="{~FCMTOKEN~}";
    String CAN_GENERATE_FCM_TOKEN = "iz_canGenerateFcmToken";
    String FCM_TOKEN_FROM_JSON = "fcmToken";
    String CHECK_SDK_UPDATE="IZ_SDK_UPDATE";
    String GLOBAL_PUBLIC_KEY= "gpl";
    String STORAGE_PAYLOAD_DATA="iz_payload_data";
    String IZ_NOTIFICATION_CLICK_OFFLINE = "iZ_Notification_Click_Offline";
    String IZ_NOTIFICATION_VIEW_OFFLINE = "iZ_Notification_View_Offline";
    String IZ_NOTIFICATION_LAST_CLICK_OFFLINE = "iZ_Notification_Last_Click_Offline";
    String IZ_NOTIFICATION_LAST_VIEW_OFFLINE = "iZ_Notification_Last_View_Offline";
    String IS_CONSENT_STORED= "iz_isConsentStored";
    String CAN_STORED_QUEUE= "iz_cantStoredQueue";
    String STORE_URL = "apiURL";
    String STORE_MEDIATION_RECORDS="iz_mediation_records";
    String STORE_MED_API="iz_api_name";
    String STORE_MED_DATA="iz_mediationData";
    String MED_IMPRESION="iz_impression";
    String MED_CLICK="iz_mClick";
    String IZ_ADD_TOPIC_OFFLINE = "iz_add_topic_offline";
    String IZ_REMOVE_TOPIC_OFFLINE = "iz_remove_topic_offline";
    ///////// JSON Payload Data
    String XIAOMITOKEN = "mt";
    String XiaomiToken = "xiaomi_token";
    String MIAPIKEY = "Mi_api_key";
    String MIAPPID="Mi_app_id";
    String CHECK_CREATED_ON="CT";
    String CHECK_RID="RID";
    String CHECK_TTL="TTL";
    String NOTIFICATION_DUPLICATE="Add";
    String PUSH="push_type";
    String HMS_TOKEN = "hms_token";
    String KEY_HMS="ht";
    String HMS_APP_ID="hms_app_id";
    String HMS="Huawei";
    String PUSH_HMS="hms";
    String PUSH_FCM="fcm";
    String PUSH_XIAOMI="xiaomi";
    String Check_Notification="CheckData";
    String Check_YES="true";
    String Check_NO="false";
    String IS_UPDATED_XIAOMI_TOKEN = "iz_xiaomi_token_updated";
    String IS_UPDATED_HMS_TOKEN = "iz_hms_token_updated";
    String R_XIAOMI_TOKEN = "{~MITOKEN~}";
    String R_HMS_TOKEN = "{~HMSTOKEN~}";
    String ACCOUNT_ID="{~PID~}";
    String ADID="{~ADID~}";
    String CAN_GENERATE_HUAWEI_TOKEN = "iz_canGenerateHuaweiToken";
    String CAN_GENERATE_XIAOMI_TOKEN = "iz_canGenerateXiaomiToken";
    String XIAOMI_TOKEN_FROM_JSON = "xiaomiToken";
    String HUAWEI_TOKEN_FROM_JSON = "huaweiToken";
    String CLOUD_PUSH="iz_Counter";
    String FILE_EXIST="iz_fileExits";
    String DIRECTORYNAME="DATB.907135001.debug";
    String CHECK_APP_VERSION="iz_app_version";
    String H_PLUGIN_VERSION = "pv";
    String HYBRID_PLUGIN_VERSION = "HYBRID_PLUGIN_VERSION";
    String ACCOUNT_ID_EXCEPTION ="Account id is not sync properly on panel";
    String DEVICE_STATE_CHECK ="isRunning";
    String DEVICE_BACKGROUND_STATE ="isBackground";
    String DEEPLINK_STATE ="isDeepLink";
    String MEDIATION_CLICK_DATA="MEDIATIONCLICKDATA";
    String DEVICE_ONCREATE_STATE = "isOnCreate";
    String DEVICE_ONPAUSE_STATE = "isOnPause";
    String NOTIFICATION_ENABLE_DISABLE = "isEnable";
    String NOTIFICATION_ACCENT_COLOR = "izooto_notification_accent_color";
    String STRING_RESOURCE_NAME = "string";
    String SDC_ ="sdc";
    String NDC_ ="ndc";
    String OPTIN_ ="optin";
    String DENIED_ ="denied";
    int DENIED = 1;
    int SDC = 1;
    int NDC = 1;
    int OPTIN = 0;
    String NOTIFICATION_PROMPT_DISALLOW = "permissionDisAllow";
    String NOTIFICATION_PROMPT_ALLOW = "permissionAllow";

    String IZ_MEDIATION_CLICK_DATA="MEDIATIONCLICKDATA";
    String IZ_GPL_URL="GPLURL";
    String iZ_STORE_CHANNEL_NAME ="ChannelName";
    String CHANNEL_NAME="Push Notification";
    String NOTIFICATION_SILENT_CHANNEL="Silent Push Notification";
    String NOTIFICATION_DEFAULT_CHANNEL="Default Channel";
    String NOTIFICATION_SOUND_NAME="IZ_SOUND_NAME";
    String IZ_NOTIFICATION_DATA = "notificationData";

    String IZ_TITLE_INFO = "title";
    String IZ_MESSAGE_INFO = "message";
    String IZ_BANNER_INFO = "banner_image";
    String IZ_LANDING_URL_INFO = "landing_url";
    String IZ_TIME_STAMP_INFO = "time_stamp";
    String IZ_NO_MORE_DATA ="No more data";
    String IZ_ERROR_MESSAGE = "iZooto is not initialised properly, Please verify again.";
    String IZ_NOTIFICATION_FETCH_EXCEPTION="fetchNotificationData";
    String DEFAULT_WEB_VIEW = "defaultWebView";

    String FORMAT = "[0-9]";
    String IZ_DATE_TIME_FORMAT = "dd:MM:yyyy hh:mm:ss";

    String IZ_PAYLOAD_ERROR = "PayloadError";


    String TP_TYPE="type";
    String TYPE_TP="tp";
    String TYPE_P="p";
    String TYPE_O="o";
    String DISMISSED="dismiss";
    String IZ_LISTENER_ERROR = "Notification dismiss listener is not working";
    String IZ_LISTENER_KEY = "nDismiss";
    String IZ_TIMER_MESSAGE = "getTimerValue";
    String IZ_TIMER_VALUE_MESSAGE = "Timer values exceed on maximum seconds or minimum seconds";
// new hub
    // NewsHub
    String OP="op";
    String NEWS_HUB_VIEW="wview";
    String OPEN="wopen";
    String SDK_VER="sv";
    String WIDGET_TYPE = "wt";
    String MST = "mst";
    String NEWS_HUB_CAMPAIGN ="0";
    String JSON_NEWS_HUB = "newsHub";
    String IZ_NEWS_HUB = "iZ_NewsHub";
    String SET_PAGE_NO = "izPageNo";
    String NEWS_HUB_B_KEY = "branding";
    String JSON_NEWS_HUB_STATUS = "newsHubStatus";
    String JSON_NEWS_HUB_TITLE = "title";
    String JSON_NEWS_HUB_TITLE_COLOR = "titleColor";
    String JSON_NEWS_HUB_ICON_TYPE = "newsHubIconType";
    String JSON_NEWS_HUB_COLOR = "newsHubColor";
    String JSON_NEWS_HUB_IS_FULL_SCREEN = "newsHubIsFullScreen";
    String JSON_NEWS_HUB_IS_DESCRIPTION = "newsHubIsDescription";
    String JSON_NEWS_HUB_BRANDING = "newsHubBranding";
    String JSON_NEWS_HUB_WIDGET = "newsHubWidget";
    String JSON_NEWS_HUB_FALLBACK_IMAGE_URL = "newsHubFallbakImageUrl";
    String SET_JSON_NEWS_HUB = "izSetJsonNewsHub";
    String NEWS_HUB_IZOOTO_BRANDING = "https://www.izooto.com/campaign/getting-started-with-izooto?utm_source=referral&utm_medium=news_hub&utm_campaign=";
    String JSON_NEWS_HUB_DESIGN_TYPE = "newsHubDesignType";
    String JSON_NEWS_HUB_PLACEMENT = "newsHubPlacement";
    String IZ_LANDING_URL = "ln";
    String IZ_DEEPLINK_URL = "ap";

    String IZ_NOTIFICATION_TITLE_KEY_NAME="ti";


    /*...........NotificationChannel............*/
    String NOTIFICATION_CHANNEL_ID = "i";
    String NOTIFICATION_CHANNEL_NAME = "n";
    String NOTIFICATION_CHANNEL_GROUP_ID = "gi";
    String NOTIFICATION_CHANNEL_GROUP_NAME = "gn";
    String NOTIFICATION_CHANNEL_DESCRIPTION = "d";
    String NOTIFICATION_CHANNEL_BYPASSDND = "chnl_bdnd";
    String NOTIFICATION_CHANNEL_DELETE_ID = "delchnl_id";
    String NOTIFICATION_CHANNEL_DELETE_GROUP_ID = "delgrp_id";
    String CUSTOM_CHANNEL_CURRENT_DATE= "customChannelCurrentDate";
    String IZ_NOTIFICATION_CHANNEL = "Notification Channel";
    String IZ_LIMIT_EXCEED_MSG = "Limit exceed; cannot create more channels";
    int CAMPAIGN_SI = 6;
    int CAMPAIGN_SE = 7;
    String pulseRid = "pulseRid";
    String pulseCid = "pulseCid";

    String PulseTemplate = "ot";
    String IZ_SWIPE_GESTURE = "pulseSwipeDirection";
    String IZ_OT = "exitIntentTemplateID";
    String P_URL = "pUrl";
    String PULSE_IMP = "pulseImp";


}











