package com.izooto;

public interface ShortpayloadConstant {
    String CAMPNAME = "cd";
    String CREATEDON= "ct";
    String FETCHURL = "fu";
    String KEY = "k";
    String ID ="id";
    String RID= "r";
    String LINK ="ln";
    String TITLE = "t";
    String SUBTITLE = "st";
    String GROUP = "gp";
    String BADGE_COUNT = "bct";
    String NMESSAGE = "m";
    String ICON = "i";
    String REQINT = "ri";
    String TAG= "tg";
    String BANNER = "bi";
    String ACTNUM= "b";
    String BADGE_ICON= "bic";
    String BADGE_COLOR= "bc";
    String ACT1NAME= "b1";
    String ACT1LINK= "l1";
    String ACT2NAME= "b2";
    String ACT2LINK= "l2";
    String INAPP= "ia";
    String TARYICON="ti"; //tray icon
    String ICONCOLOR="ic";// icon color
    String SOUND= "su";//sound
    String LEDCOLOR="lc"; // led color
    String VISIBILITY = "vi"; //visibilty
    String GKEY = "gk";
    String GMESSAGE="gm";
    String PROJECTNUMBER="pn";// project nUmber
    String COLLAPSEID = "ci";// collapseID
    String PRIORITY="pi";
    String RAWDATA="rawData";
    String ADDITIONALPARAM ="ap";
    String PAYLOAD ="Payload";
    String ACT1ICON="ib1";
    String ACT2ICON="ib2";
    String ACT1ID="d1";
    String ACT2ID ="d2";
    String CFG="cfg";
    String CPC="cpc";
    String RV="rv";
    String RC="rc";
    String Passive_Flag="pf";
    String CPM="cpm";
    String CTR="ctr";
    String RECEIVED_BID="rb";
    String AD_TYPE="tp";
    String AD_ID="id";
    String FALLBACK_SUB_DOMAIN="fsd";
    String FALL_BACK_DOMAIN="fbd";
    String FAll_BACK_PATH="fbu";
    String TIME_OUT="to";
    String AD_TIME_OUT="to";
    String NOTIFICATIONSOUND="su";
    String MAX_NOTIFICATION="mn";
    String CUSTOM_NOTIFICATION="cn";

}
